/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleDNSSD */

#ifndef _Included_com_apple_dnssd_AppleDNSSD
#define _Included_com_apple_dnssd_AppleDNSSD
#ifdef __cplusplus
extern "C" {
#endif
#undef com_apple_dnssd_AppleDNSSD_MORE_COMING
#define com_apple_dnssd_AppleDNSSD_MORE_COMING 1L
#undef com_apple_dnssd_AppleDNSSD_DEFAULT
#define com_apple_dnssd_AppleDNSSD_DEFAULT 4L
#undef com_apple_dnssd_AppleDNSSD_NO_AUTO_RENAME
#define com_apple_dnssd_AppleDNSSD_NO_AUTO_RENAME 8L
#undef com_apple_dnssd_AppleDNSSD_SHARED
#define com_apple_dnssd_AppleDNSSD_SHARED 16L
#undef com_apple_dnssd_AppleDNSSD_UNIQUE
#define com_apple_dnssd_AppleDNSSD_UNIQUE 32L
#undef com_apple_dnssd_AppleDNSSD_BROWSE_DOMAINS
#define com_apple_dnssd_AppleDNSSD_BROWSE_DOMAINS 64L
#undef com_apple_dnssd_AppleDNSSD_REGISTRATION_DOMAINS
#define com_apple_dnssd_AppleDNSSD_REGISTRATION_DOMAINS 128L
#undef com_apple_dnssd_AppleDNSSD_MAX_DOMAIN_NAME
#define com_apple_dnssd_AppleDNSSD_MAX_DOMAIN_NAME 1009L
#undef com_apple_dnssd_AppleDNSSD_ALL_INTERFACES
#define com_apple_dnssd_AppleDNSSD_ALL_INTERFACES 0L
#undef com_apple_dnssd_AppleDNSSD_LOCALHOST_ONLY
#define com_apple_dnssd_AppleDNSSD_LOCALHOST_ONLY -1L
/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    ConstructName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSSD_ConstructName
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    ReconfirmRecord
 * Signature: (IILjava/lang/String;II[B)V
 */
JNIEXPORT void JNICALL Java_com_apple_dnssd_AppleDNSSD_ReconfirmRecord
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint, jbyteArray);

/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    GetNameForIfIndex
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apple_dnssd_AppleDNSSD_GetNameForIfIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    GetIfIndexForName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSSD_GetIfIndexForName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    InitLibrary
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSSD_InitLibrary
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
