/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleBrowser */

#ifndef _Included_com_apple_dnssd_AppleBrowser
#define _Included_com_apple_dnssd_AppleBrowser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleBrowser
 * Method:    CreateBrowser
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleBrowser_CreateBrowser
  (JNIEnv *, jobject, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
