/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleDNSRecord */

#ifndef _Included_com_apple_dnssd_AppleDNSRecord
#define _Included_com_apple_dnssd_AppleDNSRecord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleDNSRecord
 * Method:    Update
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSRecord_Update
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_apple_dnssd_AppleDNSRecord
 * Method:    Remove
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSRecord_Remove
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
