/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleRegistration */

#ifndef _Included_com_apple_dnssd_AppleRegistration
#define _Included_com_apple_dnssd_AppleRegistration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleRegistration
 * Method:    BeginRegister
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I[B)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleRegistration_BeginRegister
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jstring, jstring, jint, jbyteArray);

/*
 * Class:     com_apple_dnssd_AppleRegistration
 * Method:    AddRecord
 * Signature: (II[BILcom/apple/dnssd/AppleDNSRecord;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleRegistration_AddRecord
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
