/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleResolver */

#ifndef _Included_com_apple_dnssd_AppleResolver
#define _Included_com_apple_dnssd_AppleResolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleResolver
 * Method:    CreateResolver
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleResolver_CreateResolver
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
