/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleQuery */

#ifndef _Included_com_apple_dnssd_AppleQuery
#define _Included_com_apple_dnssd_AppleQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleQuery
 * Method:    CreateQuery
 * Signature: (IILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleQuery_CreateQuery
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
