/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleService */

#ifndef _Included_com_apple_dnssd_AppleService
#define _Included_com_apple_dnssd_AppleService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleService
 * Method:    BlockForData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleService_BlockForData
  (JNIEnv *, jobject);

/*
 * Class:     com_apple_dnssd_AppleService
 * Method:    ProcessResults
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleService_ProcessResults
  (JNIEnv *, jobject);

/*
 * Class:     com_apple_dnssd_AppleService
 * Method:    HaltOperation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apple_dnssd_AppleService_HaltOperation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
