/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleDomainEnum */

#ifndef _Included_com_apple_dnssd_AppleDomainEnum
#define _Included_com_apple_dnssd_AppleDomainEnum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleDomainEnum
 * Method:    BeginEnum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDomainEnum_BeginEnum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
