/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleRecordRegistrar */

#ifndef _Included_com_apple_dnssd_AppleRecordRegistrar
#define _Included_com_apple_dnssd_AppleRecordRegistrar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleRecordRegistrar
 * Method:    CreateConnection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleRecordRegistrar_CreateConnection
  (JNIEnv *, jobject);

/*
 * Class:     com_apple_dnssd_AppleRecordRegistrar
 * Method:    RegisterRecord
 * Signature: (IILjava/lang/String;II[BILcom/apple/dnssd/AppleDNSRecord;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleRecordRegistrar_RegisterRecord
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint, jbyteArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
