syntax = "proto3";

message ClientIdentifier {
  string id = 1;
}

message Dot {
  int64 client_identifier_index = 1;
  int64 position = 2;
}

message VectorClock {
  repeated int64 positions = 1;
}

enum Message_Type {
  STOP_CONNECTION = 0;
  CURRENT_STATE = 1;
  REQUEST_VERSIONS = 2;
  SEND_VERSIONS = 3;
}

message Message {
  Message_Type type = 1;
  repeated ClientIdentifier clients = 2;

  VectorClock clock = 3;
  repeated Dot request_version_dots = 4;
  repeated Operation send_version_operations = 5;
}

message Operation {
  VectorClock clock = 1;
  int64 client_index = 2;
  Action action = 3;
}

enum ActionType {
  AddCharacter = 0;
  ChangeName = 1;
  ChangeInitiative = 2;
  ChangePlayerCharacterToPlayer = 3;
  ChangePlayerCharacterToNonPlayer = 4;
  DeleteCharacter = 5;
  ResetAllInitiatives = 6;
  StartTurn = 7;
  FinishTurn = 8;
  Die = 9;
  Delay = 10;
  ResolveConflicts = 11;
}

message Action {
  ActionType actionType = 1;
  CharacterId characterId = 2;

  Dot TurnActionPredecessor = 3;

  sint32 Initiative = 4;

  Dot ChangeNameInsertAfterDot = 5;
  int32 ChangeNameInsertAfterChar = 6;

  Dot ChangeNameDeleteDot = 7;
}

message CharacterId {
  string id = 1;
}
