on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $ANDROID_SDK_ROOT ENV; ls /usr/local/lib/android/sdk
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command gradle assembleRelease