name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Or your desired JDKversion
          distribution: 'temurin'

      - name: Build and Deploy
        run: ./gradlew wasmJsBrowserDistribution
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./composeApp/build/dist/wasmJs/productionExecutable
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
